spring:
  application:
    name: zuul-notification

server:
  port: 30010

eureka:
  client:
    service-url:
      defaultZone: http://eureka-demo:8030/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

zuul:
  routes:
    zuul:
      path: /zuulApi/**
      service-id: zuul-notification

    price:
      path: /api/v1/notifyservice/**
      service-id: ts-notification-service
      strip-prefix: false
  sensitive-headers:

ribbon:
  ConnectionTimeout: 10000
  ReadTimeout: 600000